name: GO | Telegram Webhook Router

on:
  push:
    branches: [ golang-2.0 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/telegram_webhook_router:dev-golang
      - name: Login in DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}
      - name: Pushing docker image
        run: docker push ${{ secrets.DOCKER_USER }}/telegram_webhook_router:dev-golang